### DISCUSSION TITLE
Make an Unraid package to run server on unraid for local network

### DISCUSSION THREAD

**Discussion by an303042** [ptrumpis/snap-camera-server#74] [Ideas]
Hi, 
Thanks for your work!
My daughters are very attached to their SnapCamera lenses from the Covid lockdown period, and now are unable to use them on their computers.
I would like to run the snap camera server on my unraid server and have their computer access that over my home network rather then run an instance of the server on each laptop. 
Unraid has its own community app store, but really its just a repackaged docker of sorts (it can also install dockers from docker hub and other sources I think, but not sure about directly from github).
I'm still trying to figure out how to do all this with whats currently available, but figured I'd let you know about my use case since it might apply to other as well.
Thanks again!

Edit: it seems you can package a docker in github as well, and then unraid can pull directly from github. see - https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-docker-registry

**Comment by ptrumpis** [comment]
Hi, thanks for sharing your idea.

The easiest way to run the server is `docker compose`.

I just published the project to Github's Docker registry (experimentally).

You would have to manually configure a mysql database server and a webserver with SSL files.
You would also have to set the environment variables, either by `.env` file or by passing them as arguments to the container.

**Comment by an303042** [comment]
Thanks for that!
I'll do my best to get it working. Hopefully I'll be up to the task.

**Comment by goines** [comment]
Thanks for this. I was just looking to get the lenses working on desktop again, and I also already have a separate headless linux box running docker compose for a few things.  It would be great to slightly separate the instructions to cover network cases like that. For example, I'm running nginx manager already and it'll easily produce real certificates to handle messages, and then I only have to point my clients at the DNS server with those entries. They should work almost the same as real and only the docker server would need updating.

This is additionally beneficial when dealing with corporate based laptop/desktop clients that can have restrictions on running VMs locally (docker).

Thanks for putting this project together!

**Comment by goines** [comment]
In the case of using docker-compose with an existing docker instance and only wanting the `snap-camera-server` container, is that what `ghcr.io/ptrumpis/snap-camera-server:latest` would give me, or would it give me the entire project with the dependencies?

I'd love to be able to modify my existing `docker-compose.yml` to have something like:
```
  snap-camera-server:
    image: ghcr.io/ghcr.io/ptrumpis/snap-camera-server:latest
    container_name: snap-camera-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - /.../config:/config
      - /.../whatever_is_needed:/whatever_is_needed
    ports:
      - ... : ...
    restart: unless-stopped
```
And then just add in the various paths to line up with nginx (or nginx manager) mysql, etc.  Maybe that's already the way it installs? I just wanted to double check before I start digging into the requirements.  For example, if you're using nginx to handle the key/cer files, does the snap-camera-server need anything to do with the certs itself? Or can nginx handle it all and you just have to ensure DNS or hosts files point to the right address on the clients?

**Reply by ptrumpis** [reply]
Hey, I updated my previous post, things should be more clear now.
But to clarify further:

The docker image will give you the snap camera server only, no nginx or mysql.
So you can use it with an existing instance of nginx (or any other webserver) and mysql (or mariadb).

You just need to set the enivornment vars in the `.env` file (those commented out at the bottom)

Of course you can also pass them inside `docker-compose.yml`.
(Using your example from above)
```yaml
  snap-camera-server:
    image: ghcr.io/ghcr.io/ptrumpis/snap-camera-server:latest
    container_name: snap-camera-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${MYSQL_DOCKER_PORT}
      - PORT=5645
      - STORAGE_SERVER=http://studio-app.snapchat.com
      - STORAGE_PATH=/var/lib/snapcamera
      - IMPORT_DIR=import
      - MEDIA_DIR=snap-camera-media
      - MEDIA_DIR_ALT=snap-camera-media-alt
    volumes:
      - /.../config:/config
      - /.../whatever_is_needed:/whatever_is_needed
    ports:
      - ... : ...
    restart: unless-stopped

```

**Additional setup tasks:**
You need to manually create the database schema in your database [db_schema.sql](https://github.com/ptrumpis/snap-camera-server/blob/main/mysql/db_schema.sql)

And you need to manually upload and configure SSL files to your webserver.
You will also have to configure the upstream to the snap camera server.

See this nginx configuration as reference [default.conf.template](https://github.com/ptrumpis/snap-camera-server/blob/main/nginx/default.conf.template)
(Remove and replace placeholders like `${HTTP_PORT}, ${WWW_ROOT}, ${WEBAPP}`)

By default you need to use the port 443 for SSL.
If the port is already occupied by another site you need to patch your binary to disable HTTPS.
(I currently don't know of any way to change the port)

See this [post/discussion](https://github.com/ptrumpis/snap-camera-server/discussions/24#discussioncomment-5676381) on how to patch out HTTPS.
(In this case you will not need any SSL files)
