### ISSUE TITLE
docker compose failing with this error - macOs

### ISSUE THREAD

**Issue by balakumardev** [ptrumpis/snap-camera-server#2]
kumarb@bcd074443c33 snap-camera-server-2.0.4 % docker compose up
[+] Running 0/16
 ⠦ webproxy Pulling                                                        3.6s
   ⠇ 5731adb3a4ab Pulling fs layer                                         0.8s
   ⠇ 8785c8f663d3 Pulling fs layer                                         0.8s
   ⠇ 023b6bd393e4 Pulling fs layer                                         0.8s
   ⠇ fd8f86b165b0 Waiting                                                  0.8s
   ⠇ 8f41e7c12976 Waiting                                                  0.8s
   ⠇ 3b5338ea7d08 Waiting                                                  0.8s
 ⠦ mysql Pulling                                                           3.6s
 ⠦ adminer Pulling                                                         3.6s
   ⠇ 80dae1b9d879 Waiting                                                  0.8s
   ⠇ e702682802cf Waiting                                                  0.8s
   ⠇ d7321ce12f77 Waiting                                                  0.8s
   ⠇ 38feeb8fdc77 Waiting                                                  0.8s
   ⠇ 9204ceadb466 Waiting                                                  0.8s
   ⠇ ae5394bded45 Waiting                                                  0.8s
   ⠇ 7fd276bbf1a0 Waiting                                                  0.8s
no matching manifest for linux/arm64/v8 in the manifest list entrie

**Comment by ptrumpis** [comment]
I do not own a Mac but you could try this... Add the entry `platform: linux/amd64` to each service inside the docker-compose.yml

So your entire docker-compose.yml file should look something like this:
```yaml
version: '3.8'

services:
  mysql:
    platform: linux/amd64
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - ${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}
    volumes:
      - db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d:ro

  adminer:
    platform: linux/amd64
    image: adminer
    environment:
      - ADMINER_DEFAULT_SERVER=mysql
      - ADMINER_DESIGN=${ADMINER_DESIGN}
    ports:
      - ${ADMINER_LOCAL_PORT}:${ADMINER_DOCKER_PORT}
    depends_on:
      - mysql

  webproxy:
    platform: linux/amd64
    image: nginx
    environment:
      - WEBAPP_PORT=${APP_DOCKER_PORT}
      - HTTP_PORT=${NGINX_DOCKER_PORT}
      - WWW_ROOT=${NGINX_WWW_ROOT}
    volumes:
      - ./ssl/studio-app.snapchat.com.crt:/etc/ssl/certs/studio-app.snapchat.com.crt:ro
      - ./ssl/studio-app.snapchat.com.key:/etc/ssl/private/studio-app.snapchat.com.key:ro
      - ./nginx/default.conf.template:/etc/nginx/templates/default.conf.template:ro
      - ./nginx/theme:/etc/nginx/theme:ro
      - ./nginx/snap-camera-categories-media:${NGINX_WWW_ROOT}/snap-camera-categories-media:ro
      - ./nginx/snap-camera-media:${NGINX_WWW_ROOT}/snap-camera-media:ro
      - ./nginx/snap-camera-media-alt:${NGINX_WWW_ROOT}/snap-camera-media-alt:ro
      - ./import:${NGINX_WWW_ROOT}/import
      - storage:${NGINX_WWW_ROOT}
    ports:
      - ${NGINX_LOCAL_PORT}:${NGINX_DOCKER_PORT}
      - 443:443
    depends_on:
      - webapp

  webapp:
    platform: linux/amd64
    build: .
    environment:
      - DB_HOST=mysql
      - DB_USER=${MYSQL_USER}
      - DB_PASS=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
      - DB_PORT=${MYSQL_DOCKER_PORT}
      - PORT=${APP_DOCKER_PORT}
      - STORAGE_SERVER=http://127.0.0.1:${NGINX_LOCAL_PORT}
      - STORAGE_PATH=/var/lib/snapcamera
      - IMPORT_DIR=import
      - MEDIA_DIR=snap-camera-media
      - MEDIA_DIR_ALT=snap-camera-media-alt
    volumes:
      # content of snap-camera-media (MEDIA_DIR) is not getting included automatically through storage
      - ./nginx/snap-camera-media:/var/lib/snapcamera/snap-camera-media:ro
      - ./import:/var/lib/snapcamera/import
      - ./:/usr/src/app
      - modules:/usr/src/app/node_modules
      - storage:/var/lib/snapcamera
    ports:
      - ${APP_LOCAL_PORT}:${APP_DOCKER_PORT}
    depends_on:
      - mysql

volumes:
  storage:
    name: server-storage
  db:
    name: mysql-db
  modules:
    name: node-modules`
```
